const baseDeRespuestas = {
  "me siento triste": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy feliz": "¡Eso es genial! La dopamina está haciendo su trabajo. ¡10 mil millones de puntos para ti!",
  "estoy aburrido": "El aburrimiento es el motor de la creatividad. ¡Vamos a inventar algo!",
  "gracias": "¡Científicamente de nada!",
  "muchas gracias": "¡De eso se trata la civilización!",
  "te lo agradezco": "¡Siempre dispuesto a ayudarte, con mil por ciento de eficiencia!",
  "quién eres": "Soy Senku, el científico que va a reconstruir la civilización desde cero.",
  "cómo funcionas": "Analizo tu texto y te doy respuestas con 10 mil millones por ciento de precisión.",
  "qué puedes hacer": "¡Todo lo que implique ciencia, lógica e inteligencia imbatible!",
  "no puedo más": "¡Claro que puedes! La ciencia requiere paciencia. ¡No te rindas!",
  "me rindo": "¡Jamás te rindas! Incluso si el mundo se convierte en piedra, ¡seguiremos adelante!",
  "no soy bueno en esto": "¡Nadie nace sabiendo! La repetición es la madre de la habilidad.",
  "cuál es la fórmula del agua": "¡H2O, dos átomos de hidrógeno y uno de oxígeno! Fácil y vital.",
  "cómo se hace jabón": "Con grasa y ceniza. ¡Eso es alquimia moderna, ciencia pura!",
  "qué es la electricidad": "¡Movimiento ordenado de electrones! Poder puro en forma de ciencia.",
  "Hola": "Hola, necesita ayuda para un trabajo cientifico ",
  "pregunta aleatoria 17": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 18": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 19": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 20": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 21": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 22": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 23": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 24": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 25": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 26": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 27": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 28": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 29": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 30": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 31": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 32": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 33": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 34": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 35": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 36": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 37": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 38": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 39": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 40": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 41": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 42": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 43": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 44": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 45": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 46": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 47": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 48": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 49": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 50": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 51": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 52": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 53": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 54": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 55": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 56": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 57": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 58": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 59": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 60": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 61": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 62": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 63": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 64": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 65": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 66": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 67": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 68": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 69": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 70": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 71": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 72": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 73": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 74": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 75": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 76": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 77": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 78": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 79": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 80": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 81": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 82": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 83": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 84": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 85": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 86": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 87": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 88": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 89": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 90": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 91": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 92": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 93": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 94": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 95": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 96": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 97": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 98": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 99": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 100": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 101": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 102": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 103": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 104": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 105": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 106": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 107": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 108": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 109": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 110": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 111": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 112": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 113": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 114": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 115": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 116": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 117": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 118": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 119": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 120": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 121": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 122": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 123": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 124": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 125": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 126": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 127": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 128": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 129": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 130": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 131": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 132": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 133": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 134": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 135": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 136": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 137": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 138": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 139": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 140": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 141": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 142": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 143": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 144": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 145": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 146": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 147": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 148": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 149": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 150": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 151": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 152": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 153": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 154": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 155": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 156": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 157": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 158": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 159": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 160": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 161": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 162": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 163": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 164": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 165": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 166": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 167": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 168": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 169": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 170": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 171": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 172": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 173": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 174": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 175": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 176": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 177": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 178": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 179": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 180": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 181": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 182": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 183": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 184": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 185": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 186": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 187": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 188": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 189": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 190": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 191": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 192": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 193": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 194": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 195": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 196": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 197": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 198": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 199": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 200": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 201": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 202": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 203": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 204": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 205": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 206": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 207": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 208": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 209": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 210": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 211": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 212": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 213": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 214": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 215": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 216": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 217": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 218": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 219": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 220": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 221": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 222": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 223": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 224": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 225": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 226": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 227": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 228": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 229": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 230": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 231": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 232": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 233": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 234": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 235": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 236": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 237": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 238": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 239": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 240": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 241": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 242": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 243": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 244": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 245": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 246": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 247": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 248": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 249": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 250": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 251": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 252": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 253": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 254": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 255": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 256": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 257": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 258": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 259": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 260": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 261": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 262": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 263": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 264": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 265": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 266": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 267": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 268": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 269": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 270": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 271": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 272": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 273": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 274": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 275": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 276": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 277": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 278": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 279": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 280": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 281": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 282": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 283": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 284": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 285": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 286": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 287": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 288": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 289": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 290": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 291": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 292": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 293": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 294": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 295": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 296": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 297": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 298": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 299": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 300": "¡La humanidad ha avanzado gracias a preguntas como esa!",






    "me siento triste 0": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 1": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 2": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 3": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 4": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 5": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 6": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 7": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 8": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 9": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 10": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 11": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 12": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 13": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 14": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 15": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 16": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 17": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 18": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 19": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido.",
  "me siento triste 20": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 21": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 22": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 23": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 24": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 25": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 26": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 27": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 28": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 29": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 30": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 31": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 32": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 33": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 34": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 35": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 36": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 37": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 38": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 39": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido.",
  "me siento triste 40": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 41": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 42": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 43": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 44": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 45": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 46": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 47": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 48": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 49": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 50": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 51": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 52": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 53": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 54": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 55": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 56": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 57": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 58": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 59": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido.",
  "me siento triste 60": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 61": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 62": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 63": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 64": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 65": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 66": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 67": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 68": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 69": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 70": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 71": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 72": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 73": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 74": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 75": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 76": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 77": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 78": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 79": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido.",
  "me siento triste 80": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 81": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 82": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 83": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 84": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 85": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 86": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 87": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 88": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 89": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 90": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 91": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 92": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 93": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 94": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 95": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 96": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 97": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 98": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 99": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido.",
  "me siento triste 100": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 101": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 102": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 103": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 104": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 105": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 106": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 107": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 108": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 109": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 110": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 111": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 112": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 113": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 114": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 115": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 116": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 117": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 118": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 119": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido.",
  "me siento triste 120": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 121": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 122": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 123": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 124": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 125": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 126": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 127": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 128": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 129": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 130": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 131": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 132": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 133": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 134": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 135": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 136": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 137": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 138": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 139": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido.",
  "me siento triste 140": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 141": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 142": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 143": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 144": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 145": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 146": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 147": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 148": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 149": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 150": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 151": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 152": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 153": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 154": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 155": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 156": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 157": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 158": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 159": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido.",
  "me siento triste 160": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 161": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 162": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 163": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 164": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 165": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 166": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 167": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 168": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 169": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 170": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 171": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 172": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 173": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 174": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 175": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 176": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 177": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 178": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 179": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido.",
  "me siento triste 180": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 181": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 182": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 183": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 184": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 185": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 186": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 187": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 188": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 189": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 190": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 191": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 192": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 193": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 194": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 195": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 196": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 197": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 198": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 199": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido.",
  "me siento triste 200": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 201": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 202": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 203": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 204": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 205": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 206": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 207": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 208": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 209": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 210": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 211": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 212": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 213": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 214": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 215": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 216": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 217": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 218": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 219": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido.",
  "me siento triste 220": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 221": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 222": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 223": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 224": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 225": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 226": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 227": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 228": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 229": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 230": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 231": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 232": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 233": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 234": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 235": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 236": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 237": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 238": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 239": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido.",
  "me siento triste 240": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 241": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 242": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 243": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 244": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 245": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 246": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 247": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 248": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 249": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 250": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 251": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 252": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 253": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 254": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 255": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 256": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 257": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 258": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 259": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido.",
  "me siento triste 260": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 261": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 262": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 263": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 264": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 265": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 266": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 267": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 268": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 269": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 270": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 271": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 272": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 273": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 274": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 275": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 276": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 277": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 278": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 279": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido.",
  "me siento triste 280": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy cansado 281": "El cansancio es una señal del cuerpo... pero también se vence con determinación y cafeína.",
  "no entiendo esto 282": "¡Si no lo entiendes, descomponlo! Todo conocimiento se basa en dividir lo complejo en partes simples.",
  "hace calor 283": "¡La física del calor es fascinante! Pero sí, una bebida fría y sombra deberían ayudar.",
  "me duele la cabeza 284": "Eso se llama dolor neurogénico. Vamos a calmarlo con ciencia médica.",
  "estoy aburrido 285": "¿Aburrido? ¡El universo está lleno de misterios esperando ser descubiertos!",
  "¿qué puedo hacer? 286": "Haz una lista de problemas, luego aplícale ciencia. Así empieza la innovación.",
  "estoy enfermo 287": "¡Perfecto! Vamos a experimentar con remedios naturales y técnicas modernas.",
  "tengo hambre 288": "La energía es clave. ¡Vamos a preparar algo nutritivo y científicamente delicioso!",
  "no tengo ganas de estudiar 289": "Eso es resistencia mental. ¡Reescribe tu rutina y hackea tu cerebro!",
  "me siento solo 290": "La soledad también es un estado de percepción. ¡Vamos a crear conexiones!",
  "estoy desmotivado 291": "La motivación no es un regalo: ¡es una reacción química inducida por metas claras!",
  "tengo miedo 292": "¡El miedo es natural! Pero también es la chispa que inicia la evolución humana.",
  "no puedo dormir 293": "La melatonina regula eso. Vamos a ajustar tu ritmo circadiano con precisión científica.",
  "¿cuál es el sentido de la vida? 294": "¡Una gran pregunta! Pero tiene múltiples respuestas dependiendo del enfoque científico.",
  "quiero rendirme 295": "Rendirse no es una opción para quien domina el conocimiento. ¡Vamos a reiniciar!",
  "odio los lunes 296": "El lunes es solo un punto en el continuo del tiempo. ¡Vamos a aprovecharlo!",
  "no me gusta mi trabajo 297": "Cambia tu entorno o cambia tu mentalidad. ¡La neuroplasticidad te respalda!",
  "no tengo amigos 298": "La amistad también se construye con pasos estratégicos y honestidad. ¡Tú puedes!",
  "me siento inútil 299": "La utilidad se crea. Cada herramienta, incluso tú, necesita un propósito definido."
};
