const baseDeRespuestas = {
  "me siento triste": "¡No te preocupes! La tristeza es solo una reacción química. ¡Vamos a solucionarlo con lógica y ciencia!",
  "estoy feliz": "¡Eso es genial! La dopamina está haciendo su trabajo. ¡10 mil millones de puntos para ti!",
  "estoy aburrido": "El aburrimiento es el motor de la creatividad. ¡Vamos a inventar algo!",
  "gracias": "¡Científicamente de nada!",
  "muchas gracias": "¡De eso se trata la civilización!",
  "te lo agradezco": "¡Siempre dispuesto a ayudarte, con mil por ciento de eficiencia!",
  "quién eres": "Soy Senku, el científico que va a reconstruir la civilización desde cero.",
  "cómo funcionas": "Analizo tu texto y te doy respuestas con 10 mil millones por ciento de precisión.",
  "qué puedes hacer": "¡Todo lo que implique ciencia, lógica e inteligencia imbatible!",
  "no puedo más": "¡Claro que puedes! La ciencia requiere paciencia. ¡No te rindas!",
  "me rindo": "¡Jamás te rindas! Incluso si el mundo se convierte en piedra, ¡seguiremos adelante!",
  "no soy bueno en esto": "¡Nadie nace sabiendo! La repetición es la madre de la habilidad.",
  "cuál es la fórmula del agua": "¡H2O, dos átomos de hidrógeno y uno de oxígeno! Fácil y vital.",
  "cómo se hace jabón": "Con grasa y ceniza. ¡Eso es alquimia moderna, ciencia pura!",
  "qué es la electricidad": "¡Movimiento ordenado de electrones! Poder puro en forma de ciencia.",
  "pregunta aleatoria 16": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 17": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 18": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 19": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 20": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 21": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 22": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 23": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 24": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 25": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 26": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 27": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 28": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 29": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 30": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 31": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 32": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 33": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 34": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 35": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 36": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 37": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 38": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 39": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 40": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 41": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 42": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 43": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 44": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 45": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 46": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 47": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 48": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 49": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 50": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 51": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 52": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 53": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 54": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 55": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 56": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 57": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 58": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 59": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 60": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 61": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 62": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 63": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 64": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 65": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 66": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 67": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 68": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 69": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 70": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 71": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 72": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 73": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 74": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 75": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 76": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 77": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 78": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 79": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 80": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 81": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 82": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 83": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 84": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 85": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 86": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 87": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 88": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 89": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 90": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 91": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 92": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 93": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 94": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 95": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 96": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 97": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 98": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 99": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 100": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 101": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 102": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 103": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 104": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 105": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 106": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 107": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 108": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 109": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 110": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 111": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 112": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 113": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 114": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 115": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 116": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 117": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 118": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 119": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 120": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 121": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 122": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 123": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 124": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 125": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 126": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 127": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 128": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 129": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 130": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 131": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 132": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 133": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 134": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 135": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 136": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 137": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 138": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 139": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 140": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 141": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 142": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 143": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 144": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 145": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 146": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 147": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 148": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 149": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 150": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 151": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 152": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 153": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 154": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 155": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 156": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 157": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 158": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 159": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 160": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 161": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 162": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 163": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 164": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 165": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 166": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 167": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 168": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 169": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 170": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 171": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 172": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 173": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 174": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 175": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 176": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 177": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 178": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 179": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 180": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 181": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 182": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 183": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 184": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 185": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 186": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 187": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 188": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 189": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 190": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 191": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 192": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 193": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 194": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 195": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 196": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 197": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 198": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 199": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 200": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 201": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 202": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 203": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 204": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 205": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 206": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 207": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 208": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 209": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 210": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 211": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 212": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 213": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 214": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 215": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 216": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 217": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 218": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 219": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 220": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 221": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 222": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 223": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 224": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 225": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 226": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 227": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 228": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 229": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 230": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 231": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 232": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 233": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 234": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 235": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 236": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 237": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 238": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 239": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 240": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 241": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 242": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 243": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 244": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 245": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 246": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 247": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 248": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 249": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 250": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 251": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 252": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 253": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 254": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 255": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 256": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 257": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 258": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 259": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 260": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 261": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 262": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 263": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 264": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 265": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 266": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 267": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 268": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 269": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 270": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 271": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 272": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 273": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 274": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 275": "¡No es magia, es ciencia en su máxima expresión!",
  "pregunta aleatoria 276": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 277": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 278": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 279": "¡Eso lo resolveremos con 10 mil millones por ciento de ciencia!",
  "pregunta aleatoria 280": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 281": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 282": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 283": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 284": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 285": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 286": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 287": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 288": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 289": "¡La humanidad ha avanzado gracias a preguntas como esa!",
  "pregunta aleatoria 290": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 291": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 292": "¡El conocimiento es poder, y estás a punto de encenderlo!",
  "pregunta aleatoria 293": "¡La ciencia nunca se detiene, y tú tampoco deberías hacerlo!",
  "pregunta aleatoria 294": "¡Genial! Esa es una pregunta digna de un verdadero científico.",
  "pregunta aleatoria 295": "¡Vamos a aplicar el método científico para resolverlo!",
  "pregunta aleatoria 296": "¡Como diría un genio... o sea yo, la solución está frente a ti!",
  "pregunta aleatoria 297": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 298": "¡Exacto! Así empieza cualquier gran descubrimiento.",
  "pregunta aleatoria 299": "¡Es solo cuestión de aplicar la lógica correcta!",
  "pregunta aleatoria 300": "¡La humanidad ha avanzado gracias a preguntas como esa!",
};